### ISSUE TITLE
Why are we speaking english?

### ISSUE THREAD

**Issue by eduardomoroni** [CaronaBoard/caronaboard-native#28]
Hey folks, vocês não acham que deixar as conversas do nosso repositório todo em inglês pode dificultar a participação de pessoas que não são confiantes com seu inglês? Para nós que temos uma certa vivência é até tranquilo, mas se a nossa ideia é rodar um workshop e depois abrir para Open source. Não seria melhor falarmos em português?

**Comment by viniciusrdacosta** [comment]
Chegando por último, e já sentando na janela, acredito que seremos mais inclusivo se utilizarmos o português como a linguagem principal.

Até porque o App está em português, certo ? Pelo menos a versão web dele está.

**Comment by taniadgv** [comment]
Vamos falar português então.
