### ISSUE TITLE
Esqueci Minha Senha

### ISSUE THREAD

**Issue by eduardomoroni** [CaronaBoard/caronaboard-native#38]
Dado que o usuário inseriu o e-mail e esqueceu a senha
Quando clicar em "Esqueci minha senha" na tela de Login
Então deve receber um email com o link do firebase para trocar a senha e ser notificado na UI que o link foi enviado

**Comment by henriquelbsouza** [comment]
Trabalhando nisso c/ @otaviormachado

**Comment by henriquelbsouza** [comment]
#52 PR Criado
