### ISSUE TITLE
Criar uma Carona Desejada

### ISSUE THREAD

**Issue by eduardomoroni** [CaronaBoard/caronaboard-native#41]
Carona Desejada - quando um _passageiro_ proativamente cadastra sua _carona desejada_ para que _motoristas_ possam vê-la.

Cenário: "Não tenho carro e preciso de caronas"

Observação:
- Estória não envolve criar tela parar isso, somente preparar a funcionalidade no firebase a na comunicação entre a app e o firebase.

**Comment by ehkasper** [comment]
peguei

**Comment by eduardomoroni** [comment]
Foi implementado em: https://github.com/CaronaBoard/caronaboard-native/pull/51.
