### ISSUE TITLE
Tela de lista das caronas desejadas

### ISSUE THREAD

**Issue by taniadgv** [CaronaBoard/caronaboard-native#47]
Dado que um usuario acesse a app 
Quando clicar em _caronas desejadas_
Então deve ser exibida a lista de _caronas desejadas_ criadas pelos usuários

Dado que um _passageiro_ esteja na tela de lista de _caronas desejadas_
Quando a tela exibir uma _carona desejada_ criada por si
Então deve ser exibido um ícone que permita ao _passageiro_ alterar a _carona desejada_ 

Dado que um _passageiro_ esteja na tela de lista de _caronas desejadas_
Quando a tela exibir uma _carona desejada_ criada por si e que tenha sido aceita por um _motorista_
Então o ícone de edição deve estar desabilitado

Depende da estória #41 

Observações:
- a princípio, cada item da lista de _caronas desejadas_ terá todas as informações suficientes da carona e não será necessário criar uma tela de detalhes da carona.

**Comment by deckerjeferson** [comment]
Oi :)

**Comment by yaliscouto** [comment]
peguei
