### ISSUE TITLE
Editar perfil de usuário

### ISSUE THREAD

**Issue by gustavomazevedo** [CaronaBoard/caronaboard-native#50]
Dado que um usuário está logado
Quando entrar na tela do seu perfil
Então deve poder editar os seus dados e Salvar

![caronaboard_editar_perfil](https://user-images.githubusercontent.com/85676/29590857-52e7eb74-8772-11e7-8680-2d78244a0ca4.png)

**Comment by obxhdx** [comment]
Vitor e Obedi pareando
